"""empty message

Revision ID: 22515be4d7e4
Revises: a4c085ece7ed
Create Date: 2022-11-30 11:59:27.269153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22515be4d7e4'
down_revision = 'a4c085ece7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['skin_color'])
        batch_op.create_unique_constraint(None, ['eye_color'])
        batch_op.create_unique_constraint(None, ['height'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['climate'])
        batch_op.create_unique_constraint(None, ['gravity'])
        batch_op.create_unique_constraint(None, ['surface_water'])
        batch_op.create_unique_constraint(None, ['rotation_period'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('climate')
        batch_op.drop_column('gravity')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
