"""empty message

Revision ID: 7a7c2c996afa
Revises: 860a5dcb2cdb
Create Date: 2022-11-29 12:44:58.138910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7c2c996afa'
down_revision = '860a5dcb2cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_birth_year_key', type_='unique')
        batch_op.drop_constraint('characters_gender_key', type_='unique')
        batch_op.drop_constraint('characters_name_key', type_='unique')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_name_key', type_='unique')
        batch_op.drop_constraint('planets_population_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_population_key', ['population'])
        batch_op.create_unique_constraint('planets_name_key', ['name'])

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('characters_name_key', ['name'])
        batch_op.create_unique_constraint('characters_gender_key', ['gender'])
        batch_op.create_unique_constraint('characters_birth_year_key', ['birth_year'])

    # ### end Alembic commands ###
