"""empty message

Revision ID: 860a5dcb2cdb
Revises: 844d58e86176
Create Date: 2022-11-29 12:42:27.444995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860a5dcb2cdb'
down_revision = '844d58e86176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_eye_color_key', type_='unique')
        batch_op.drop_constraint('characters_height_key', type_='unique')
        batch_op.drop_constraint('characters_skin_color_key', type_='unique')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('height')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_climate_key', type_='unique')
        batch_op.drop_constraint('planets_gravity_key', type_='unique')
        batch_op.drop_constraint('planets_rotation_period_key', type_='unique')
        batch_op.drop_constraint('planets_surface_water_key', type_='unique')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('gravity')
        batch_op.drop_column('climate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('planets_surface_water_key', ['surface_water'])
        batch_op.create_unique_constraint('planets_rotation_period_key', ['rotation_period'])
        batch_op.create_unique_constraint('planets_gravity_key', ['gravity'])
        batch_op.create_unique_constraint('planets_climate_key', ['climate'])

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('characters_skin_color_key', ['skin_color'])
        batch_op.create_unique_constraint('characters_height_key', ['height'])
        batch_op.create_unique_constraint('characters_eye_color_key', ['eye_color'])

    # ### end Alembic commands ###
